const Cupon = require('../../domain/entities/cupon.entity');
const { NotFoundError } = require('../../domain/errors');

class CuponService {
    constructor(cuponRepository) { 
        this.cuponRepository = cuponRepository;
    }
    
    async getAllCupons() {
        return this.cuponRepository.getAll();
    }

    async getCuponById(id) {
        const cupon = await this.cuponRepository.getById(id);
        if (!cupon) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }
        return cupon;
    }

    async createCupon(cuponData) {
        const cuponEntity = new Cupon(
            null, // ID is null because it will be generated by the database
            cuponData.tipoDescuento, //tipo Porcentaje del total o monto fijo
            cuponData.valorDescuento, //Porcentaje o monto
            cuponData.idProducto, //Producto a aplicar el descuento
            cuponData.fechaIni, //fecha de inicio de la vigencia del cupon
            cuponData.fechaFin, //fecha de finalización de la vigencia del cupon
            cuponData.estado //Si esta vigente, expirado
        );
        return this.cuponRepository.create(cuponEntity);
    }

    async updateCupon(id, cuponData) {
        const existingCupon = await this.cuponRepository.getById(id);
        if (!existingCupon) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }

        const cuponEntity = new Cupon(
            id,
            cuponData.tipoDescuento, //tipo Porcentaje del total o monto fijo
            cuponData.valorDescuento, //Porcentaje o monto
            cuponData.idProducto, //Producto a aplicar el descuento
            cuponData.fechaIni, //fecha de inicio de la vigencia del cupon
            cuponData.fechaFin, //fecha de finalización de la vigencia del cupon
            cuponData.estado //Si esta vigente, expirado
        );
        return this.cuponRepository.update(id, cuponEntity);
    }

    async deleteCupon(id) {
        const cupon = await this.cuponRepository.getById(id);
        if (!cupon) {
            throw new NotFoundError(`Cupon with id ${id} not found`);
        }
        return this.cuponRepository.delete(id);
    }
}
module.exports = CuponService;